### ISSUE TITLE
playback speed issue when playing from internet

### ISSUE THREAD

**Issue by bachig26** [tomasklaen/uosc#488] opened 2023-03-30 14:42 UTC
I tried playing a video from internet with and without the uosc, but when I'm using uosc the video gets played in like 3-4x playback speed and i haven't changed any related functions in the lua file and checked the config file.

I'm looking for help and possibiliy fix for this if it's a bug.

**Comment by hooke007** [comment] 2023-03-30 16:23
display-resample would speed up the playback only if your Vsync is off.
But this is not mpv's issue, user must make sure Vsync on their side.

**Comment by alexpandain** [comment] 2023-04-05 13:39
I'm also getting issue while playing videos from my nginx server

**Comment by tomasklaen** [comment] 2023-04-05 14:26
Can someone provide steps to reproduce?

**Comment by tomasklaen** [comment] 2023-04-05 15:27
Can you also isolate the issue? Minimal uosc/mpv config + url or mpv cli parameters to open that wold reproduce it.

I really don't want to go back and forth asking for settings and install & reverse engineer mov-cli to see what it's doing.

**Comment by hooke007** [comment] 2023-04-05 15:39
> But this issue happens in other situations where one plays a url in mpv with uosc.

Never happened here.

**Comment by bachig26** [comment] 2023-04-05 16:02
> Can you also isolate the issue? Minimal uosc/mpv config + url or mpv cli parameters to open that wold reproduce it.
> 
> I really don't want to go back and forth asking for settings and install & reverse engineer mov-cli to see what it's doing.

i'm attaching my config but i even tried with minimal uosc (i.e vanilla uosc with any other scripts) and i also tried one config pack where i use uosc with latest commits. i'm seeing this issue on everyone of them.

[portable_config.zip](https://github.com/tomasklaen/uosc/files/11160728/portable_config.zip)

**Comment by hooke007** [comment] 2023-04-05 16:13
Could you offer a simpliest method to reproduce? (i.e. direct link to one online video)
BTW, your conf works fine here. Still cannot reproduce.

**Comment by tomasklaen** [comment] 2023-04-05 17:12
We need some url or even better cli parameters to pass to mpv that reproduces the issue.

I also use uosc to watch youtube videos often and never had this happen.

**Comment by bachig26** [comment] 2023-04-05 17:15
> We need some url or even better cli parameters to pass to mpv that reproduces the issue.
> 
> I also use uosc to watch youtube videos often and never had this happen.

youtube streaming works fine, but not sure about any direct url....i'll let you know once i find one that reproduces this issue.

**Comment by aicynide** [comment] 2023-04-05 20:16
@bachig26 mov-cli use very very slow server thats why video buffers

**Comment by aicynide** [comment] 2023-04-05 20:30
@tomasklaen this video buffers more in uosc than vanilla https://m.papaonwork.workers.dev/1:/Avengers%20Endgame%20(2019)%201080p%20%5B3D%5D%20Half-SBS%20BluRay%20x264%20AVC%20%5BOrg%20Hindi%20DDP%205.1%20~%20640Kbps%20+%20English%20TrueHD%20Atmos%207.1%5D%20ESubs%20~%20FGT.mkv

**Comment by aicynide** [comment] 2023-04-05 20:39
https://soft-truth-8658.nekax29261.workers.dev/e7f3e4bb4e677ca40d0871a99ef827b8/drivebot.fun/Parasite.(2019).1080p.BluRay.REMUX.x264.AVC.[Org.AMZN.Hindi.DDP.5.1.~.640kbps.+.Korean.DTS-HDMA.TrueHD.Atmos.7.1].ESub.~.FGT.mkv

**Comment by tomasklaen** [comment] 2023-04-05 21:03
These seem to play fine for me. And what do you mean by "buffers more"? I thought the complaint was that the videos play faster than they should?

Either way it just doesn't make sense to me. uosc is not setting or changing anything related to buffering or speed. We just read the current values and display them.

**Comment by mon** [comment] 2023-09-29 14:34
I've replicated this with an RTSP stream from an IP camera.

It is caused by setting `video-sync=display-resample`, as recommended by the README to fix sluggish UI tied to video framerate.

I have also replicated this without uosc installed, so it's not technically a uosc problem, _however_ the README implies it's a good setting to turn on.

I suggest modifying the README to include this caveat, as (like myself), I think most users would see "A little higher CPU/GPU load??? I have plenty to spare! Let's turn it on!"

Some more discussion about the flag causing issues, there's probably more if you search:
https://github.com/mpv-player/mpv/issues/5917

**Comment by christoph-heinrich** [comment] 2023-09-29 14:54
If `video-sync=display-resample` causes videos to play too fast for you, then that's certainly a bug in mpv and you should open an issue about it over there.

FWIW I'm unable to replicate that issue.

Are you using KWin and have the video span multiple monitors? Because there is an issue about that https://github.com/mpv-player/mpv/issues/10489

**Comment by mon** [comment] 2023-09-29 15:00
Personally, I'm on Windows, so KWin is irrelevant ;) I'm on a chocolatey install, which is quite old at `v2023.01.28`, so it may have been fixed in the last 8 months... Or maybe not! Just sharing what I found, as all symptoms match.

**Comment by tomasklaen** [comment] 2023-09-30 15:25
I'll close this as not a uosc issue, but feel free to add context here if needed.

**Closed by tomasklaen** 2023-09-30 15:25 UTC
