### ISSUE TITLE
[suggestion] fuzzy finding entries in the playlist menu

### ISSUE THREAD

**Issue by junguler** [tomasklaen/uosc#514] opened 2023-04-19 10:48 UTC
some of my folders contain 100s of videos and it would be really helpful to have the option of fuzzy finding them, i think something like this would require a way to temporarily disable other keybinds inside the playlist menu, not really sure about the mechanics of it

this script [mpv-iptv](https://github.com/gthreepw00d/mpv-iptv) has something similar but for iptv files (m3u, m3u8) , not sure if it's helpful or not as i'm a complete noob

also on a side note i know your script is able to populate playlists but not sure how it differs from the autoload.lua script, can it find and add every item in a folder? is it able to shuffle playlist items without duplicating them unlike the autoload.lua script?

**Comment by tomasklaen** [comment] 2023-04-19 11:29
Duplicate of #198.

uosc doesn't populate playlist. The `items` menu simply displays the playlist, and if there isn't one, it displays the list of files in current file's directory. Same for `autoload` and `next/prev` navigation commands. They use either playlist with seamless fallback to current directory.

uosc's shuffle than simply picks a random file from these lists. It doesn't random-shuffle anything.

**Closed by tomasklaen** 2023-04-19 11:29 UTC

**Comment by junguler** [comment] 2023-04-19 11:42
i understand, thanks for the quick reply
