### ISSUE TITLE
[bug] timeline might crash if track's `duration` is incorrect

### ISSUE THREAD

**Issue by hooke007** [tomasklaen/uosc#188] opened 2022-09-11 19:38 UTC
![Snipaste_2022-09-11_20-34-49](https://user-images.githubusercontent.com/41094733/189545946-da578433-d978-46b3-85f9-33255b154f06.jpg)

**Comment by christoph-heinrich** [comment] 2022-09-11 20:23
I don't really know how you managed to do this, as for me the timeline is always hidden in the beginning when the video hasn't loaded yet, but try this patch to see if it fixes it.
``` diff
diff --git a/scripts/uosc.lua b/scripts/uosc.lua
index e3726b4..589e61e 100644
--- a/scripts/uosc.lua
+++ b/scripts/uosc.lua
@@ -2600,7 +2600,7 @@ Elements:add(Element.new('pause_indicator', {
 	end,
 }))
 Elements:add(Element.new('timeline', {
-	enabled = true,
+	enabled = false,
 	pressed = false,
 	size_max = 0, size_min = 0, -- set in `on_display_change` handler based on `state.fullormaxed`
 	size_min_override = options.timeline_start_hidden and 0 or nil, -- used for toggle-progress command
```

**Comment by christoph-heinrich** [comment] 2022-09-11 20:45
I managed to reproduce it now.

**Comment by hooke007** [comment] 2022-09-11 20:56
> if it fixes it.

Nope.

**Comment by christoph-heinrich** [comment] 2022-09-11 21:21
I have a fix now, but I don't like it and I also don't really like the alternative.
``` diff
diff --git a/scripts/uosc.lua b/scripts/uosc.lua
index e3726b4..fcc108e 100644
--- a/scripts/uosc.lua
+++ b/scripts/uosc.lua
@@ -954,6 +954,7 @@ function Element:off(name, handler)
 end
 
 function Element:trigger(name, ...)
+	if not self.enabled and name:match('mouse') then return end
 	self:maybe('on_' .. name, ...)
 	if self._eventListeners[name] == nil then return end
 	for _, handler in ipairs(self._eventListeners[name]) do handler(...) end
```
This basically disables all mouse events for all disabled elements.
Alternatively we could add a `if not this.enabled then return end` at the beginning of all relevant functions in the timeline.

I reproduced it in two different but similar ways.
1. open mpv with a playlist (so e.g. opening a folder)
2. Fullscreen on your right monitor (technically optional, but makes it easier)
3. Put mouse at the end of the timeline and and
    - click repeatedly
    - hold down left mouse button and drag the mouse a little bit up and down

If you get the timing right, so that mpv switches to the next file, but hasn't loaded the next file yet before new mouse input comes in, you get a crash.

**Comment by hooke007** [comment] 2022-09-11 21:26
> I have a fix now, but I don't like it and I also don't really like the alternative.

Hmm, not work for my case.

**Comment by hooke007** [comment] 2022-09-11 21:33
> Load any RAW AAC and seek to random timestamp.

To be specific, if seeking to the time which is longer than it should be, it would crash.
E.g. My sample is 23:00 but ffmpeg reported its duration is longer than 1 hour. When I seek to some time over 23:00, it would crash.

**Comment by christoph-heinrich** [comment] 2022-09-11 21:37
I don't have one of such files at hand, so I can't test exactly what you're experiencing.

But based on your screenshot the cause of the crash is that the timeline calls `set_from_cursor` because of a mouse event, while `state.duration` is `nil`. The timeline gets disabled as soon as `state.duration` or `state.time` are nil, so disabling mouse events for disabled elements should also prevent the crash. And that's exactly what it is doing for the way I was testing it.

**Comment by hooke007** [comment] 2022-09-11 21:45
[track1_[und]_DELAY 0ms.zip](https://github.com/tomasklaen/uosc/files/9543598/track1_.und._DELAY.0ms.zip)

Here is another sample that you could test. Its real duration should be 4:51.

**Comment by christoph-heinrich** [comment] 2022-09-11 21:53
Seeking beyond the real duration doesn't crash for me, not even without my posted fix using [this exact file](https://github.com/tomasklaen/uosc/blob/main/scripts/uosc.lua), Doesn't matter if it's that file alone or in a playlist.

**Comment by hooke007** [comment] 2022-09-11 22:09
I found the offender here.
I totally cleaned my config folder and found that leaving the `idle=yes` alone in mpv.conf would make uosc crash in that case.

**Comment by christoph-heinrich** [comment] 2022-09-11 22:16
Interestingly using `idle=yes` alone also crashes for me, but combining it with `keep-open=yes` prevents it from crashing.

**Comment by tomasklaen** [comment] 2022-09-13 08:29
I did some mouse event tweaks in the recent refactor that makes mouse related events not be dispatched to disabled elements so this shouldn't happen anymore. Can someone confirm?

**Comment by hooke007** [comment] 2022-09-13 09:24
No crash log but cannot call up the bottom tool.

**Comment by tomasklaen** [comment] 2022-09-13 09:32
If time or duration is not available, timeline won't show up, because there is nothing it can render. Or are you saying they are available and it still doesn't show up? I'd really need some example video with these issues.

**Comment by hooke007** [comment] 2022-09-13 09:41
Here is the [test file](https://github.com/tomasklaen/uosc/issues/188?notification_referrer_id=NT_kwDOAnMOTbM0Mzc4MDczMzA1OjQxMDk0NzMz#issuecomment-1243049207)

Both timeline and control buttons don't show up when seeking [out of range](https://github.com/tomasklaen/uosc/issues/188?notification_referrer_id=NT_kwDOAnMOTbM0Mzc4MDczMzA1OjQxMDk0NzMz#issuecomment-1243047430).

**Comment by tomasklaen** [comment] 2022-09-13 10:19
What's happening is that when you seek after the real duration, mpv closes the file. Nothing we can do about it on our side.

The controls were not visible because there was a bug where if timeline gets disabled while it's being hovered, its proximity stops updating, and controls were accessing the old values telling them that it's still hovered. This was fixed in the commit above.

So I guess this puzzle is solved now.

**Closed by tomasklaen** 2022-09-13 10:19 UTC
