### ISSUE TITLE
how to disable #menu: and just use #!

### ISSUE THREAD

**Issue by candrapersada** [tomasklaen/uosc#837] opened 2024-01-18 06:42 UTC
how to disable `#menu:` and just use `#!` context menu uosc?

**Comment by hooke007** [comment] 2024-01-19 01:04
No. Why?

**Comment by tomasklaen** [comment] 2024-01-20 20:38
Does anyone remember why do we even support `#menu:`? Can't check since searching for `"#menu:"` returns 10 pages of closed issues :)

**Comment by Sneakpeakcss** [comment] 2024-01-20 21:03
> Does anyone remember why do we even support `#menu:`? Can't check since searching for `"#menu:"` returns 10 pages of closed issues :)

That's the `mpv.net` context menu syntax that was initially added in https://github.com/tomasklaen/uosc/pull/68, so i guess for compatibility sake to avoid turning `input.conf` into a big mess if you want to use both at the same time:

![image](https://github.com/tomasklaen/uosc/assets/77424331/4ef6a5b3-d7a4-4460-a177-c91f78aabd41)

And now it's also used by [mpv-menu-plugin](https://github.com/tsl0922/mpv-menu-plugin) ([wiki](https://github.com/tsl0922/mpv-menu-plugin/wiki/Configuration))

**Comment by tomasklaen** [comment] 2024-01-20 21:14
Oh, so it was added specifically for what this issue is complaining about? How do we resolve this?

@candrapersada why do you not want uosc to just use your already defined menu?

**Comment by Sneakpeakcss** [comment] 2024-01-20 21:51
I guess the issue is about splitting them to have different commands in each contextmenu. I also thought about this before, but wasn't bothered to do it.

`mpv.net` recently added an [option](https://github.com/mpvnet-player/mpv.net/blob/main/docs/manual.md#--menu-syntaxvalue) to choose either `#menu:` or `#!` syntax, but even then `uosc` will just populate the contexmenu with `#menu:`, so from what i understand it's not possible to achieve currently.

Though this could probably be achieved with easily maintained local edit by removing it from here(?):

https://github.com/tomasklaen/uosc/blob/2eccc1bb068ff959cc17b444b11e6bdaf34795d7/src/uosc/lib/menus.lua#L376-L382

I didn't look much into `mpv-menu-plugin`, but it probably doesn't have an option for this, though it only uses the same `#menu:` prefix, so the issue would be the same.

**Comment by tsl0922** [comment] 2024-02-05 06:12
The [same issue](https://github.com/tsl0922/mpv-menu-plugin/issues/37) was closed as not planed in mpv-menu-plugin.

I can't find a usecase for it, 2 different context menu? why

**Comment by Sneakpeakcss** [comment] 2024-02-05 08:44
> The [same issue](https://github.com/tsl0922/mpv-menu-plugin/issues/37) was closed as not planed in mpv-menu-plugin.
> 
> I can't find a usecase for it, 2 different context menu? why

For me it was because i prefer the positioning of the `mpv.net` context menu… I barely ever use the one provided by `uosc`, but `mpv.net` doesn’t support keyboard navigation, which `uosc` does, and does it very, very well with its ‘type-to-search’ function.

*Not to mention that in case of `mpv.net` you can't open it with `show-menu` command unless the mouse cursor is on top of the window.*

So, the idea was to keep the `uosc` context menu and use it more like a 'favourite-most-used-options-menu' mostly for keyboard exclusive navigation.

No clue what the issue author had in mind though.

**Comment by tsl0922** [comment] 2024-02-05 09:03
@Sneakpeakcss it's not hard to implement what you want, but what you want for menu is not a menu, it's more like a command palette.

uosc's `menu` is more like a dialog that looks like menu, with some limitation (ex: always in center), I don't use it as menu too.

I'd like to use uosc as command palette (like sublime text), but you can't change menu position and width, maybe writing a new standalone command palette script is better.

**Comment by Sneakpeakcss** [comment] 2024-02-05 11:20
> @Sneakpeakcss it's not hard to implement what you want, but what you want for menu is not a menu, it's more like a command palette.
> 
> uosc's `menu` is more like a dialog that looks like menu, with some limitation (ex: always in center), I don't use it as menu too.
> 
> I'd like to use uosc as command palette (like sublime text), but you can't change menu position and width, maybe writing a new standalone command palette script is better.

Yea, basically the reason why i didn't even bother to do the mentioned local edit to split them. Couldn't bother to make a separate `uosc` script that displays a menu with my 'favourite-commands' and ended up just using the whole menu as is, with occasional use of [keybinds](https://github.com/tomasklaen/uosc?tab=readme-ov-file#keybinds) command palette. The initial idea was mostly a lazy convenience to keep doing it from `input.conf`.

I would love to be able to change the `uosc` width(size?) and align the menu to a certain position (top-left / left), it would be very convenient for certain menu scripts.

___

In this whole issue i personally don't see any other use-case than the one i've mentioned, so the question seems to be: "should uosc bother to support this for covenience?" Kinda falls under the mentioned "edit it locally if you really want such a thing" from my perspective.

**Comment by tomasklaen** [comment] 2024-02-06 09:25
Don't see a use case to define two different context menus, on the other hand there's plenty of people who want uosc to just pick up their mpv.net menu and vice versa. The author is also AWOL, so I think I'll close this.

**Closed by tomasklaen** 2024-02-06 09:25 UTC
