### ISSUE TITLE
Sometimes menu text is not rendered

### ISSUE THREAD

**Issue by NaiveInvestigator** [tomasklaen/uosc#354] opened 2022-10-30 12:46 UTC
![image](https://user-images.githubusercontent.com/72654596/198879043-30caa4e0-5c4c-4085-82af-118a6518a007.png)

This doesn't always happen, only sometimes randomly but also kinda frequently. Also the elements that dissappear are also random at times.

This is my menu:
```
### UOSC MENU

menu				script-binding uosc/menu
MOUSE_BTN2			script-binding uosc/menu
o				script-binding open-file-dialog					#! Open File
#				script-binding SmartCopyPaste/paste				#! Open From Clipboard
CTRL+Y				script-binding youtube-search					#! Search In YouTube
#				script-binding uosc/chapters					#! Navigation > Chapters
#				script-binding seek_to/toggle-seeker				#! Navigation > Seek To Time
#				script-binding SmartCopyPaste/copy-specific			#! Navigation > Copy Timestamp
#				script-binding SmartCopyPaste/paste-specific			#! Navigation > Paste Timestamp
CTRL+n				add audio-delay +0.10						#! Audio > Delay > Increase Audio Delay
CTRL+N				add audio-delay -0.10						#! Audio > Delay > Decrease Audio Delay
#				set audio-delay 0						#! Audio > Delay > Reset Audio Delay
#				script-binding uosc/audio-device				#! Audio > Devices
#				script-binding uosc/audio					#! Audio > Tracks
#				script-binding uosc/video					#! Video > Tracks
D				cycle deinterlace						#! Video > Toggle Deinterlace
#				set window-scale 0.5						#! Video > Window Scale > 50%
#				set window-scale 0.8						#! Video > Window Scale > 80%
#				set window-scale 1.0						#! Video > Window Scale > 100%
#				set window-scale 1.2						#! Video > Window Scale > 120%
#				set window-scale 1.5						#! Video > Window Scale > 150%
#				set window-scale 2.0						#! Video > Window Scale > 200%
# 				vf toggle vflip							#! Video > Flip > Vertical
#				vf toggle hflip							#! Video > Flip > Horizontal
n				script-binding autosubsync/autosubsync-menu			#! Subtitles > Automatic Synchronisation
#				script-binding autosub/download_subs				#! Subtitles > Download For Current Video > Language 1 (English)
#				script-binding autosub/download_subs2				#! Subtitles > Download For Current Video > Language 2 (Bengali)
'				add sub-scale +0.1						#! Subtitles > Scale > Increase Subtitle Scale
;				add sub-scale -0.1						#! Subtitles > Scale > Decrease Subtitle Scale
#				set sub-scale 1							#! Subtitles > Scale > Reset Subtitle Scale
:				add sub-pos -1							#! Subtitles > Position > Move Subtitle Up
"				add sub-pos +1							#! Subtitles > Position > Move Subtitle Down
#				set sub-pos 100							#! Subtitles > Position > Reset Subtitle Position
x				add sub-delay +0.10						#! Subtitles > Delay > Increase Subtitle Delay
y				add sub-delay -0.10						#! Subtitles > Delay > Decrease Subtitle Delay
#				set sub-delay 0							#! Subtitles > Delay > Reset Subtitle Delay
d				cycle-values deband "yes" "no"					#! Utils > Deband > Toggle Deband
#				cycle-values deband-threshold "35" "45" "60"; show-text "Deband: ${deband-iterations}:${deband-threshold}:${deband-range}:${deband-grain}" 1000			#! Utils > Deband > Deband (Weak)
#				cycle-values deband-range "20" "25" "30"; show-text "Deband: ${deband-iterations}:${deband-threshold}:${deband-range}:${deband-grain}" 1000			#! Utils > Deband > Deband (Medium)
#				cycle-values deband-grain "5" "15" "30"; show-text "Deband: ${deband-iterations}:${deband-threshold}:${deband-range}:${deband-grain}" 1000			#! Utils > Deband > Deband (Strong)
ALT+s				script-binding save-playlist					#! Utils > Save Playlist In Current Path
Ctrl+S				script-binding clipshot-subs					#! Utils > Screenshot To Clipboard > With Subtitles
#				script-binding clipshot-video					#! Utils > Screenshot To Clipboard > Video Only
#				script-binding clipshot-window					#! Utils > Screenshot To Clipboard > Whole Window 
c				script_message show-clock					#! Utils > Show Clock
>				add speed +0.25; script-binding uosc/flash-speed		#! Utils > Speed > Increase Speed
<				add speed -0.25; script-binding uosc/flash-speed		#! Utils > Speed > Decrease Speed
/				set speed 1; script-binding uosc/flash-speed			#! Utils > Speed > Reset Speed
C				change-list glsl-shaders toggle "~~/shaders/crt-mpv.glsl"	#! Utils > Toggle CRT Shader
p				script-binding webtorrent/toggle-info				#! Utils > Toggle Info About Torrent
#				set video-aspect-override "-1"					#! Aspect Ratio > Default
#				set video-aspect-override "16:9"				#! Aspect Ratio > 16:9
#				set video-aspect-override "4:3"					#! Aspect Ratio > 4:3
#				set video-aspect-override "2.35:1"				#! Aspect Ratio > 2.35:1
O				script-binding uosc/show-in-directory				#! Show in File Explorer
#				script-binding uosc/open-config-directory			#! Open Config Directory
q				quit 								#! Quit

```

**Comment by junguler** [comment] 2022-10-30 22:03
same here, seems to be related to the menu entries that also have key-binds set for them

**Comment by christoph-heinrich** [comment] 2022-10-31 00:22
I've never noticed this and it's weird that it happens randomly.

The only thing I can think of is that it for some reason thinks the title has 0 width. Are you using `text_width_estimation=no`?.

Maybe some debug output can shed some light on this.
The following patch prints all the titles, hints and their widths whenever a menu gets opened.
It would be interesting to know what gets printed for the items that don't get shown.

```diff
diff --git a/scripts/uosc_shared/elements/Menu.lua b/scripts/uosc_shared/elements/Menu.lua
index 336cbd0..f7ba065 100644
--- a/scripts/uosc_shared/elements/Menu.lua
+++ b/scripts/uosc_shared/elements/Menu.lua
@@ -209,6 +209,8 @@ function Menu:update_content_dimensions()
 			local icon_width = item.icon and self.font_size or 0
 			item.title_width = text_width(item.title, title_opts)
 			item.hint_width = text_width(item.hint, hint_opts)
+			print('title', item.title, item.title_width)
+			print('hint', item.hint, item.hint_width)
 			local spacings_in_item = 1 + (item.title_width > 0 and 1 or 0)
 				+ (item.hint_width > 0 and 1 or 0) + (icon_width > 0 and 1 or 0)
 			local estimated_width = item.title_width + item.hint_width + icon_width
```

**Comment by tomasklaen** [comment] 2022-10-31 10:26
I'm also in the "can't replicate" camp here.

**Comment by junguler** [comment] 2022-10-31 11:59
i just did a test for this issue without my uosc.conf file and it's gone, there is something in our old conf file that causes this, i don't know what but at least now i know i need to make a new config file

**Comment by NaiveInvestigator** [comment] 2022-10-31 14:40
> ```diff
> print('title', item.title, item.title_width)
> +			print('hint', item.hint, item.hint_width)
> ```
My menu this time:
![image](https://user-images.githubusercontent.com/72654596/199034058-8174eede-70f2-4974-8957-c1953a80cbd8.png)
I tried this diff and I got this in my console
```
[uosc] title Open File 93.552845114754
[uosc] hint o 11.475718032787
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Open From Clipboard 207.3533492459
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Search In YouTube 185.89749403279
[uosc] hint CTRL+Y 79.852832786885
[uosc] title Navigation 101.97078609836
[uosc] hint nil 0
[uosc] title Audio 55.153068590164
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Video 55.153068590164
[uosc] hint nil 0
[uosc] title Subtitles 82.900116983607
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Utils 42.097474622951
[uosc] hint nil 0
[uosc] title Aspect Ratio 122.50342190164
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Show in File Explorer 203.97011567213
[uosc] hint O 16.085144262295
[uosc] title Open Config Directory 213.15223396721
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Quit 39.619448655738
[uosc] hint q 11.475718032787
[uosc] title Chapters 0
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Seek To Time 0
[uosc] hint nil 0
[uosc] title Copy Timestamp 0
[uosc] hint nil 0
[uosc] title Paste Timestamp 0
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Delay 0
[uosc] hint nil 0
[uosc] title Devices 0
[uosc] hint nil 0
[uosc] title Tracks 0
[uosc] hint nil 0
[uosc] title Tracks 0
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Toggle Deinterlace 0
[uosc] hint D 14.916291803279
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Window Scale 0
[uosc] hint nil 0
[uosc] title Flip 0
[uosc] hint nil 0
[uosc] title Automatic Synchronisation 0
[uosc] hint n 11.475718032787
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Download For Current Video 0
[uosc] hint nil 0
[uosc] title Scale 0
[uosc] hint nil 0
[uosc] title Position 0
[uosc] hint nil 0
[uosc] title Delay 0
[uosc] hint nil 0
[uosc] title Deband 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] hint nil 0
[uosc] title Save Playlist In Current Path 0
[uosc] hint ALT+s 60.417606557377
[uosc] title Screenshot To Clipboard 0
[uosc] hint nil 0
[uosc] title Show Clock 0
[uosc] hint c 10.397357377049
[uosc] title Speed 0
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Toggle CRT Shader 0
[uosc] hint C 14.916291803279
[uosc] title Toggle Info About Torrent 0
[uosc] hint p 11.475718032787
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Default 0
[uosc] hint nil 0
[uosc] title 16:9 0
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title 4:3 0
[uosc] hint nil 0
[uosc] title 2.35:1 0
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Increase Audio Delay 0
[uosc] hint CTRL+n 77.522668852459
[uosc] title Decrease Audio Delay 0
[uosc] hint CTRL+N 80.963242622951
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Reset Audio Delay 0
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title 50% 0
[uosc] hint nil 0
[uosc] title 80% 0
[uosc] hint nil 0
[uosc] title 100% 0
[uosc] hint nil 0
[uosc] title 120% 0
[uosc] hint nil 0
[uosc] title 150% 0
[uosc] hint nil 0
[uosc] title 200% 0
[uosc] hint nil 0
[uosc] title Vertical 0
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Horizontal 0
[uosc] hint nil 0
[uosc] title Language 1 (English) 0
[uosc] hint nil 0
[uosc] title Language 2 (Bengali) 0
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Increase Subtitle Scale 0
[uosc] hint ' 3.991788
[uosc] title Decrease Subtitle Scale 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] hint ; 5.785788
[uosc] title Reset Subtitle Scale 0
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Move Subtitle Up 0
[uosc] hint : 5.785788
[uosc] title Move Subtitle Down 0
[uosc] hint " 7.3357180327869
[uosc] title Reset Subtitle Position 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] hint nil 0
[uosc] title Increase Subtitle Delay 0
[uosc] hint x 10.397357377049
[uosc] title Decrease Subtitle Delay 0
[uosc] hint y 10.397357377049
[uosc] title Reset Subtitle Delay 0
[uosc] hint nil 0
[uosc] title Toggle Deband 0
[uosc] hint d 11.475718032787
[uosc] title Deband (Weak) 0
[uosc] hint nil 0
[uosc] title Deband (Medium) 0
[uosc] hint nil 0
[uosc] title Deband (Strong) 0
[uosc] hint nil 0
[uosc] title With Subtitles 0
[uosc] hint Ctrl+S 58.098357442623
[uosc] title Video Only 0
[uosc] hint nil 0
[uosc] title Whole Window 0
[uosc] hint nil 0
[uosc] title Increase Speed 0
[uosc] hint > 12.101619672131
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Decrease Speed 0
[uosc] hint < 12.101619672131
[uosc] title Reset Speed 0
[uosc] hint / 5.785788
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Open File 93.552845114754
[uosc] hint o 11.475718032787
[uosc] title Open From Clipboard 207.3533492459
[uosc] hint nil 0
[uosc] title Search In YouTube 185.89749403279
[uosc] hint CTRL+Y 79.852832786885
[uosc] title Navigation 101.97078609836
[uosc] hint nil 0
[uosc] title Audio 55.153068590164
[uosc] hint nil 0
[uosc] title Video 55.153068590164
[uosc] hint nil 0
[uosc] title Subtitles 82.900116983607
[uosc] hint nil 0
[uosc] title Utils 42.097474622951
[uosc] hint nil 0
[uosc] title Aspect Ratio 122.50342190164
[uosc] hint nil 0
[uosc] title Show in File Explorer 203.97011567213
[uosc] hint O 16.085144262295
[uosc] title Open Config Directory 213.15223396721
[uosc] hint nil 0
[uosc] title Quit 39.619448655738
[uosc] hint q 11.475718032787
[uosc] title Chapters 0
[uosc] hint nil 0
[uosc] title Seek To Time 0
[uosc] hint nil 0
[uosc] title Copy Timestamp 0
[uosc] hint nil 0
[uosc] title Paste Timestamp 0
[uosc] hint nil 0
[uosc] title Delay 0
[uosc] hint nil 0
[uosc] title Devices 0
[uosc] hint nil 0
[uosc] title Tracks 0
[uosc] hint nil 0
[uosc] title Tracks 0
[uosc] hint nil 0
[uosc] title Toggle Deinterlace 0
[uosc] hint D 14.916291803279
[uosc] title Window Scale 0
[uosc] hint nil 0
[uosc] title Flip 0
[uosc] hint nil 0
[uosc] title Automatic Synchronisation 0
[uosc] hint n 11.475718032787
[uosc] title Download For Current Video 0
[uosc] hint nil 0
[uosc] title Scale 0
[uosc] hint nil 0
[uosc] title Position 0
[uosc] hint nil 0
[uosc] title Delay 0
[uosc] hint nil 0
[uosc] title Deband 0
[uosc] hint nil 0
[uosc] title Save Playlist In Current Path 0
[uosc] hint ALT+s 60.417606557377
[uosc] title Screenshot To Clipboard 0
[uosc] hint nil 0
[uosc] title Show Clock 0
[uosc] hint c 10.397357377049
[uosc] title Speed 0
[uosc] hint nil 0
[uosc] title Toggle CRT Shader 0
[uosc] hint C 14.916291803279
[uosc] title Toggle Info About Torrent 0
[uosc] hint p 11.475718032787
[uosc] title Default 0
[uosc] hint nil 0
[uosc] title 16:9 0
[uosc] hint nil 0
[uosc] title 4:3 0
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title 2.35:1 0
[uosc] hint nil 0
[uosc] title Increase Audio Delay 0
[uosc] hint CTRL+n 77.522668852459
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Decrease Audio Delay 0
[uosc] hint CTRL+N 80.963242622951
[uosc] title Reset Audio Delay 0
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title 50% 0
[uosc] hint nil 0
[uosc] title 80% 0
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title 100% 0
[uosc] hint nil 0
[uosc] title 120% 0
[uosc] hint nil 0
[uosc] title 150% 0
[uosc] hint nil 0
[uosc] title 200% 0
[uosc] hint nil 0
[uosc] title Vertical 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] hint nil 0
[uosc] title Horizontal 0
[uosc] hint nil 0
[uosc] title Language 1 (English) 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] hint nil 0
[uosc] title Language 2 (Bengali) 0
[uosc] hint nil 0
[uosc] title Increase Subtitle Scale 0
[uosc] hint ' 3.991788
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Decrease Subtitle Scale 0
[uosc] hint ; 5.785788
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Reset Subtitle Scale 0
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Move Subtitle Up 0
[uosc] hint : 5.785788
[uosc] title Move Subtitle Down 0
[uosc] hint " 7.3357180327869
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Reset Subtitle Position 0
[uosc] hint nil 0
[uosc] title Increase Subtitle Delay 0
[uosc] hint x 10.397357377049
[uosc] title Decrease Subtitle Delay 0
[uosc] hint y 10.397357377049
[uosc] title Reset Subtitle Delay 0
[uosc] hint nil 0
[uosc] title Toggle Deband 0
[uosc] hint d 11.475718032787
[uosc] title Deband (Weak) 0
[uosc] hint nil 0
[uosc] title Deband (Medium) 0
[uosc] hint nil 0
[uosc] title Deband (Strong) 0
[uosc] hint nil 0
[uosc] title With Subtitles 0
[uosc] hint Ctrl+S 58.098357442623
[uosc] title Video Only 0
[uosc] hint nil 0
[uosc] title Whole Window 0
[uosc] hint nil 0
[uosc] title Increase Speed 0
[uosc] hint > 12.101619672131
[uosc] title Decrease Speed 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] hint < 12.101619672131
[uosc] title Reset Speed 0
[uosc] hint / 5.785788
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Open File 93.552845114754
[uosc] hint o 11.475718032787
[uosc] title Open From Clipboard 207.3533492459
[uosc] hint nil 0
[uosc] title Search In YouTube 185.89749403279
[uosc] hint CTRL+Y 79.852832786885
[uosc] title Navigation 101.97078609836
[uosc] hint nil 0
[uosc] title Audio 55.153068590164
[uosc] hint nil 0
[uosc] title Video 55.153068590164
[uosc] hint nil 0
[uosc] title Subtitles 82.900116983607
[uosc] hint nil 0
[uosc] title Utils 42.097474622951
[uosc] hint nil 0
[uosc] title Aspect Ratio 122.50342190164
[uosc] hint nil 0
[uosc] title Show in File Explorer 203.97011567213
[uosc] hint O 16.085144262295
[uosc] title Open Config Directory 213.15223396721
[uosc] hint nil 0
[uosc] title Quit 39.619448655738
[uosc] hint q 11.475718032787
[uosc] title Chapters 0
[uosc] hint nil 0
[uosc] title Seek To Time 0
[uosc] hint nil 0
[uosc] title Copy Timestamp 0
[uosc] hint nil 0
[uosc] title Paste Timestamp 0
[uosc] hint nil 0
[uosc] title Delay 0
[uosc] hint nil 0
[uosc] title Devices 0
[uosc] hint nil 0
[uosc] title Tracks 0
[uosc] hint nil 0
[uosc] title Tracks 0
[uosc] hint nil 0
[uosc] title Toggle Deinterlace 0
[uosc] hint D 14.916291803279
[uosc] title Window Scale 0
[uosc] hint nil 0
[uosc] title Flip 0
[uosc] hint nil 0
[uosc] title Automatic Synchronisation 0
[uosc] hint n 11.475718032787
[uosc] title Download For Current Video 0
[uosc] hint nil 0
[uosc] title Scale 0
[uosc] hint nil 0
[uosc] title Position 0
[uosc] hint nil 0
[uosc] title Delay 0
[uosc] hint nil 0
[uosc] title Deband 0
[uosc] hint nil 0
[uosc] title Save Playlist In Current Path 0
[uosc] hint ALT+s 60.417606557377
[uosc] title Screenshot To Clipboard 0
[uosc] hint nil 0
[uosc] title Show Clock 0
[uosc] hint c 10.397357377049
[uosc] title Speed 0
[uosc] hint nil 0
[uosc] title Toggle CRT Shader 0
[uosc] hint C 14.916291803279
[uosc] title Toggle Info About Torrent 0
[uosc] hint p 11.475718032787
[uosc] title Default 0
[uosc] hint nil 0
[uosc] title 16:9 0
[uosc] hint nil 0
[uosc] title 4:3 0
[uosc] hint nil 0
[uosc] title 2.35:1 0
[uosc] hint nil 0
[uosc] title Increase Audio Delay 0
[uosc] hint CTRL+n 77.522668852459
[uosc] title Decrease Audio Delay 0
[uosc] hint CTRL+N 80.963242622951
[uosc] title Reset Audio Delay 0
[uosc] hint nil 0
[uosc] title 50% 0
[uosc] hint nil 0
[uosc] title 80% 0
[uosc] hint nil 0
[uosc] title 100% 0
[uosc] hint nil 0
[uosc] title 120% 0
[uosc] hint nil 0
[uosc] title 150% 0
[uosc] hint nil 0
[uosc] title 200% 0
[uosc] hint nil 0
[uosc] title Vertical 0
[uosc] hint nil 0
[uosc] title Horizontal 0
[uosc] hint nil 0
[uosc] title Language 1 (English) 0
[uosc] hint nil 0
[uosc] title Language 2 (Bengali) 0
[uosc] hint nil 0
[uosc] title Increase Subtitle Scale 0
[uosc] hint ' 3.991788
[uosc] title Decrease Subtitle Scale 0
[uosc] hint ; 5.785788
[uosc] title Reset Subtitle Scale 0
[uosc] hint nil 0
[uosc] title Move Subtitle Up 0
[uosc] hint : 5.785788
[uosc] title Move Subtitle Down 0
[uosc] hint " 7.3357180327869
[uosc] title Reset Subtitle Position 0
[uosc] hint nil 0
[uosc] title Increase Subtitle Delay 0
[uosc] hint x 10.397357377049
[uosc] title Decrease Subtitle Delay 0
[uosc] hint y 10.397357377049
[uosc] title Reset Subtitle Delay 0
[uosc] hint nil 0
(Paused) AV: 00:00:03 / 00:23:38 (0%) A-V:  0.000 Dropped: 4
[uosc] title Toggle Deband 0
[uosc] hint d 11.475718032787
[uosc] title Deband (Weak) 0
[uosc] hint nil 0
[uosc] title Deband (Medium) 0
[uosc] hint nil 0
[uosc] title Deband (Strong) 0
[uosc] hint nil 0
[uosc] title With Subtitles 0
[uosc] hint Ctrl+S 58.098357442623
[uosc] title Video Only 0
[uosc] hint nil 0
[uosc] title Whole Window 0
[uosc] hint nil 0
[uosc] title Increase Speed 0
[uosc] hint > 12.101619672131
[uosc] title Decrease Speed 0
[uosc] hint < 12.101619672131
[uosc] title Reset Speed 0
[uosc] hint / 5.785788
```

**Comment by NaiveInvestigator** [comment] 2022-10-31 15:26
I have tried new commits, and the issue still persists. but what I have noticed is that it only happens to those menus titles always.
Namely:
```
D				cycle deinterlace						#! Video > Toggle Deinterlace
ALT+s				script-binding save-playlist					#! Utils > Save Playlist In Current Path
Ctrl+S				script-binding clipshot-subs					#! Utils > Screenshot To Clipboard > With Subtitles
c				script_message show-clock					#! Utils > Show Clock
>				add speed +0.25; script-binding uosc/flash-speed		#! Utils > Speed > Increase Speed 
<				add speed -0.25; script-binding uosc/flash-speed		#! Utils > Speed > Decrease Speed 
/				set speed 1; script-binding uosc/flash-speed			#! Utils > Speed > Reset Speed
C				change-list glsl-shaders toggle "~~/shaders/crt-mpv.glsl"	#! Utils > Toggle CRT Shader
p				script-binding webtorrent/toggle-info				#! Utils > Toggle Info About Torrent
```
Out here the Speed Menu title gets rendered but not tis own submenues.
Alteast the issue is a bit narrowed down than before ig.

**Comment by christoph-heinrich** [comment] 2022-10-31 17:22
As suspected it thinks that a lot of the widths are 0, but I have no idea why that may be.

**Comment by hooke007** [comment] 2022-10-31 19:57
Even though I cloned your repo, I could not reproduce the issue.

**Comment by NaiveInvestigator** [comment] 2022-11-01 02:15
I tried changing the `osd-font` but to no avail sadly.
![image](https://user-images.githubusercontent.com/72654596/199143645-c145e750-53ba-423e-810f-368b7e1d21c2.png)
![image](https://user-images.githubusercontent.com/72654596/199143883-9d91752b-26dc-455a-a7a4-5d79cb8394b9.png)
![image](https://user-images.githubusercontent.com/72654596/199143580-e32e72b2-3a93-4399-a45a-3878a8157c57.png)

**Comment by tomasklaen** [comment] 2022-11-01 08:17
I wonder if there are some special characters that might be causing issues. Like `\r` or something. Menu parser should be stripping them, but I don't know anymore.

It's also weird that it only happens in submenus it seems.

**Comment by eko5624** [comment] 2022-11-12 17:13
I find the bug too. So I did some test, here are the results:

1. Only happens on windows, not on mac.

2.  Only happens on videos with external subtitles randomly.(referring to the subtitle files with the 
same name as the video files' in the same directory).

3. There is no problem with videos having internal subtitles (non-hard subtitles). 

4. Videos without subtitles tracks are also fine. 

5. Open the mpv's window first, and then drag the video file into the mpv window,  everything runs smoothly even if the videos files with external subtitles. 

6. double click the video files with external subtitles, the bug occurs randomly.

**Comment by escapezn** [comment] 2022-11-13 11:08
I went back to 4.3.0 and this bug disappeared

**Comment by tomasklaen** [comment] 2022-11-14 09:19
It looks fine for me :(

![image](https://user-images.githubusercontent.com/47283320/201621027-ff549a2b-dca4-47a2-b5f2-ceb47bc899ca.png)

And it doesn't look like it's an error in text measuring, as it really only happens when there are hints. This is so weird...

I guess we need someone who can replicate **and** dig into the code and find the cause.

> I went back to 4.3.0 and this bug disappeared

4.3.0 doesn't have text measuring, so it does just a dumb assumption that every letter is the same width, which leads to other issues.

**Comment by NaiveInvestigator** [comment] 2022-11-14 14:36
I also noticed this happens on files where there are two or more subtitles of the same language. It doesn't matter whether if it is embed with the vid or not. I also happen to use `secondary-sid=auto` in my `mpv.conf`  and the moment I commented that option out, the issue stops occurring. I also tried adding the option back and as suspected it the issues starts again. I think it has to do something with `secondary-sid`.

**Comment by hooke007** [comment] 2022-11-14 17:00
@tomasklaen I tested with the condition https://github.com/tomasklaen/uosc/issues/354#issuecomment-1313850053 and found it was introduced by this commit https://github.com/tomasklaen/uosc/commit/d8fad3306a0f6367b604694ca41580b557804528

**Comment by hooke007** [comment] 2022-11-14 17:29
@NaiveInvestigator Could you test this snapshot? This is the last "safe" version here.
https://github.com/tomasklaen/uosc/archive/26648f081a18fdf0890c9b789403e83672b1f6f6.zip

**Comment by eko5624** [comment] 2022-11-15 05:35
> @NaiveInvestigator Could you test this snapshot? This is the last "safe" version here. https://github.com/tomasklaen/uosc/archive/26648f081a18fdf0890c9b789403e83672b1f6f6.zip

This commit https://github.com/tomasklaen/uosc/commit/26648f081a18fdf0890c9b789403e83672b1f6f6 , no bug

**Comment by NaiveInvestigator** [comment] 2022-11-15 13:58
I tried this snapshot and can confirm it is safe.

**Comment by christoph-heinrich** [comment] 2022-11-19 20:13
Is someone that experiences his issue able to switch their lua runtime to see if that changes anything?
So from luajit to lua or from lua to luajit. Would be wild if that is actually somehow caused by a bug in the lua implementation.

Another thing we could try is to see if that patch makes a difference.
``` diff
diff --git a/scripts/uosc_shared/lib/text.lua b/scripts/uosc_shared/lib/text.lua
index 7c1cf4e..8518e2c 100644
--- a/scripts/uosc_shared/lib/text.lua
+++ b/scripts/uosc_shared/lib/text.lua
@@ -116,7 +116,7 @@ local function unicode_to_utf8(unicode)
 end
 
 local text_osd = mp.create_osd_overlay("ass-events")
-text_osd.compute_bounds, text_osd.hidden = true, true
+text_osd.compute_bounds, text_osd.hidden = true, false
 ---@type integer, integer
 local osd_width, osd_height = 100, 100
 mp.observe_property('osd-dimensions', 'native', function (_, dim)
@@ -134,7 +134,7 @@ local function measure_bounds(ass_text)
 end
 
 ---@type {wrap: integer; bold: boolean; italic: boolean, rotate: number; size: number}
-local bounds_opts = {wrap = 2, bold = false, italic = false, rotate = 0, size = 0}
+local bounds_opts = {wrap = 2, bold = false, italic = false, rotate = 0, size = 0, opacity = 0}
 
 ---Measure text width and normalize to a font size of 1
 ---text has to be ass safe
```
From what I remember this will reduce the performance a little bit, and it will also lead to mpv rendering completely transparent bitmaps each frame, but if it avoids issues that might be worth it.

If that still doesn't help, you could try that patch but without the `opacity = 0`.  That will lead to the measured text actually being visible and therefore certainly not a real solution, but if that actually makes a difference for you then I don't even know what we could possibly do about this (other then going back to the old way of estimating width). At that point it might some weird libass behavior something :confused:.

**Comment by eko5624** [comment] 2022-11-19 22:54
@christoph-heinrich Weird thing is if I open the mpv's window first, and then drag the video file into the mpv window, everything runs smoothly, why?

**Comment by christoph-heinrich** [comment] 2022-11-20 00:48
> @christoph-heinrich Weird thing is if I open the mpv's window first, and then drag the video file into the mpv window, everything runs smoothly, why?

Beats me. It indicates that it might be some weird timing thing, but it's odd that when it happens, it consistently happens for the title but not for the hint.

@junguler how is your new config coming along? Have you found which part of your config was causing it?

**Comment by hooke007** [comment] 2022-11-20 00:51
Not one part. Even though only one simple (in the menu) item would cause the issue.

**Comment by christoph-heinrich** [comment] 2022-12-03 20:34
Can someone please test if #383 makes a difference here?

**Comment by junguler** [comment] 2022-12-04 02:30
> Can someone please test if #383 makes a difference here?

it seems to have fixed the issue for me, i'm using this [input.conf](https://github.com/junguler/win_confs/blob/main/mpv/portable_config/input.conf#L101), windows 10, latest commit with your pr applied using github cli

**Comment by eko5624** [comment] 2022-12-04 02:41
> Can someone please test if #383 makes a difference here?

Yes, fix my issue too.

**Comment by dexeonify** [comment] 2022-12-04 02:57
It seems to fix it, but has anyone noticed that text width measurement is off again? Specifically the video title.

**Comment by escapezn** [comment] 2022-12-04 06:02
> Can someone please test if #383 makes a difference here?

Looks good to me.

**Comment by tomasklaen** [comment] 2022-12-04 08:13
Since it seems like #383 fixed it, I'm gonna close this. If someone still has issues I'll reopen.

**Comment by dyphire** [comment] 2022-12-04 08:45
> It seems to fix it, but has anyone noticed that text width measurement is off again? Specifically the video title.

Can be reproduced with https://github.com/tomasklaen/uosc/pull/383.
![image](https://user-images.githubusercontent.com/61936050/205481796-efbfa2bd-4c32-4697-81ca-519dd8f3b099.png)

**Comment by dexeonify** [comment] 2022-12-24 06:27
Can confirm that #396 returns the text width measurement behaviour before #383, while ensuring the menu text are rendered.

**Comment by tomasklaen** [comment] 2022-12-24 08:27
So was #396 the culprit, this is fixed, and can be closed now?

**Comment by dexeonify** [comment] 2022-12-25 07:15
#383 should be the culprit, #396 fixed it. Yes, it can be closed now.

**Closed** 2022-12-25 08:17 UTC
