### ISSUE TITLE
Chapter name over timeline weird text wrapping

### ISSUE THREAD

**Issue by smowtenshi** [tomasklaen/uosc#375] opened 2022-11-19 18:38 UTC
**mpv version:** 0.35.0
**uosc version:** 4.4.0

There's a possibility I overlooked something, but comparing it as described in pull #93, the whole behavior of text wrapping has changed.
![[UDF] Hyouka - 07](https://user-images.githubusercontent.com/7839556/202866043-7f96d4d6-2726-4666-a76a-c590b1d0f71b.png)

Compared to uosc version 4.0.0:
![[UDF] Hyouka - 07](https://user-images.githubusercontent.com/7839556/202866389-08c71fe1-9d91-431f-82ff-15bb1e0b10cc.png)

**Comment by christoph-heinrich** [comment] 2022-11-19 19:58
Can't reproduce :neutral_face:
In #354 the text width estimation sometimes thinks that text has 0 width while here it seems to think that text is much wider then it actually is. No idea why that sometimes fails for some people.

Everything else looks fine? Background of the title is the right width? Menu is also sized correctly?
Do you have `text_width_estimation` set to `yes` or `no`?

We recently had an issue that turned out to be a luajit bug, and now I'm awfully curious if there is a change in those text width related issues when people try using lua instead.
Do you know which one you are using?

**Comment by christoph-heinrich** [comment] 2022-11-20 00:39
I've only now noticed that the clamping of the text position seems to use the width that the text is supposed to have, which indicates that the wrapping itself actually works as it's supposed to, but I have no idea why it's then shown with only one word per line. @tomasklaen any ideas?

> [ 0.007][v][cplayer] List of enabled features: [...] lua luajit [...]

Looks like you're using luajit. I think the easiest way of trying it with lua would be to build mpv with [mpv-build](https://github.com/mpv-player/mpv-build), which should default to lua if both are available. After compilation the binary can be found in `mpv/build/mpv`. Due to my realization above I don't think it'll make a difference, but if you're still willing to try it, then at least we know for sure.

> Well, it seems no configuration of that patch and text_width_estimation (yes/no) option is able to change anything.

Thanks for testing.

**Comment by tomasklaen** [comment] 2022-11-20 08:14
This might have nothing to do with hints. It's just when title/hint cut coordinates are calculated, the title will always be hidden in favor of hint if its width is 0.

I think we should create an isolated script that does some test measurements on load and a couple half a second increments afterwards, and report circumstances where the width is measured as 0.

I have no other ideas. The only clue seems to be that this seems to happen only on asian PCs, but I have no idea what might they have in common to cause this.

**Comment by christoph-heinrich** [comment] 2022-11-20 16:45
The log from https://github.com/tomasklaen/uosc/issues/354#issuecomment-1297190975 shows it **never** happens for hint. I find it hard to believe that the timing just happens to work out like that for hundreds of items.
Also there is a pattern where it does work for some titles, then it doesn't work anymore for ~65 items, then it works again for a few titles, then again there are ~65 of them where it doesn't work, then it works again for a few, and then it stops working again for ~65 of them, then it works for a few, and once again it stops working for ~65 followed by a few that do work, after which it stops working again.
Meanwhile hints **always** work right in between the titles.

**Comment by christoph-heinrich** [comment] 2022-12-12 11:55
> Lua error: uosc/scripts/uosc.lua:13: attempt to concatenate a nil value

It fails to load it's dependencies. When I try that command I get the same thing. I guess that just doesn't work with `--script` :shrug:.

> nothing seem to work properly

Do you have a log of running mpv like you usually would but with the binary you compiled yourself?

**Comment by christoph-heinrich** [comment] 2022-12-14 22:39
I don't see anything wrong in that log, but it has tons of shader output which mine doesn't when I try to run it in as close to the same context as possible (`--vo=gpu --gpu-api=opengl --gpu-context=x11egl` and compiled with lua interpreter).

I assume "nothing seem to work properly" means it's not uosc specific? If things also don't work without uosc, then it seems like you ran into a problem with mpv itself and might want to open an issue about it over there.

**Comment by tomasklaen** [comment] 2022-12-17 10:14
Seems like not a uosc related issue after all, so I'm gonna close this. If someone figures out what is the cause of this and there's anything we can do to prevent it, like note in readme or something, let me know.

**Closed by tomasklaen** 2022-12-17 10:14 UTC
